import streamlit as st

TRANSLATIONS = {
    "English": {
        # ── app.py ──────────────────────────────────────────
        "subtitle":          "### Your AI-powered farming assistant",
        "feat_crop":         "🌱 **Crop Recommendation**\nGet crop suggestions based on your soil & location",
        "feat_disease":      "🔬 **Disease Detection**\nUpload a leaf photo to detect crop disease",
        "feat_weather":      "🌦️ **Weather Forecast**\nReal-time weather for your farm location",
        "feat_ai":           "🤖 **AI Farm Assistant**\nChat with an AI trained on agriculture",
        "feat_price":        "📈 **Price Prediction**\nForecast crop prices before you sell",
        "footer":            "Use the sidebar to navigate between features.",

        # ── Weather ─────────────────────────────────────────
        "wt_title":          "🌦️ Weather Forecast",
        "wt_subtitle":       "Get real-time weather and farming advice for your location.",
        "wt_city":           "🏙️ Enter City Name",
        "wt_city_hint":      "e.g. Pune, Mumbai, Nagpur",
        "wt_btn":            "🔍 Get Weather",
        "wt_temp":           "🌡️ Temperature",
        "wt_feels":          "Feels",
        "wt_humidity":       "💧 Humidity",
        "wt_wind":           "💨 Wind Speed",
        "wt_visibility":     "👁️ Visibility",
        "wt_advice":         "🌾 Farming Advice for Today",
        "wt_forecast":       "📅 Next 5 Hours Forecast",
        "wt_temp_short":     "Temp",
        "wt_no_city":        "Please enter a city name!",
        "wt_loading":        "Fetching weather data...",

        # ── Crop Recommendation ──────────────────────────────
        "cr_title":          "🌱 Crop Recommendation",
        "cr_subtitle":       "Fill in your soil and location details to get the best crop suggestion.",
        "cr_location":       "📍 Location & Season",
        "cr_district":       "District",
        "cr_season":         "Season",
        "cr_soil":           "Soil Type",
        "cr_soil_params":    "🧪 Soil Parameters",
        "cr_nitrogen":       "Nitrogen (N)",
        "cr_phosphorus":     "Phosphorus (P)",
        "cr_potassium":      "Potassium (K)",
        "cr_ph":             "Soil pH",
        "cr_temp":           "🌡️ Temperature (°C)",
        "cr_humidity":       "💧 Humidity (%)",
        "cr_rainfall":       "🌧️ Rainfall (mm)",
        "cr_btn":            "🔍 Recommend Crop",
        "cr_result":         "✅ Recommended Crop",
        "cr_confidence":     "Model Confidence",
        "cr_about":          "About",
        "cr_water":          "💧 Water Requirement",
        "cr_best_season":    "📅 Best Season",
        "cr_tip":            "Tip",
        "cr_loading":        "Analyzing your farm data...",

        # ── Disease Detection ────────────────────────────────
        "dd_title":          "🔬 Crop Disease Detection",
        "dd_subtitle":       "Upload a leaf image to detect disease using AI.",
        "dd_upload":         "📸 Upload Leaf Image",
        "dd_uploaded":       "📷 Uploaded Image",
        "dd_analysis":       "🧠 AI Analysis",
        "dd_healthy":        "✅ Plant is Healthy!",
        "dd_diseased":       "⚠️ Disease Detected!",
        "dd_plant":          "🌱 Plant",
        "dd_disease":        "🦠 Disease",
        "dd_confidence":     "📊 Confidence",
        "dd_top3":           "📊 Top 3 Predictions",
        "dd_treatment":      "💊 Treatment Suggestions",
        "dd_treat_err":      "🖼️ Treatment image not available",
        "dd_shops":          "🏪 Nearby Agro Shops",
        "dd_city":           "📍 Enter your city/area",
        "dd_search":         "🔍 Find Shops",
        "dd_found":          "shops found!",
        "dd_no_shops":       "No registered shop found.",
        "dd_maps":           "📍 Maps",
        "dd_local_only":     "⚠️ Disease Detection is only available when running locally.",
        "dd_run_local":      "💡 Run locally with: `streamlit run app.py`",
        "dd_google_tip":     "💡 Try 'agro shop near me' on Google Maps.",
        "dd_detail":         "Detail",
        "dd_info":           "Info",

        # ── Price Prediction ─────────────────────────────────
        "pp_title":          "📈 Crop Price Prediction",
        "pp_subtitle":       "Predict crop prices before you sell — plan smarter!",
        "pp_crop":           "🌾 Select Crop",
        "pp_season":         "📅 Select Season",
        "pp_month":          "📆 Month",
        "pp_year":           "📅 Year",
        "pp_btn":            "🔍 Predict Price",
        "pp_predicted":      "💰 Predicted Price",
        "pp_per_quintal":    "per Quintal",
        "pp_min":            "📉 Min Expected",
        "pp_max":            "📈 Max Expected",
        "pp_trend":          "📊 Price Trend — All 12 Months",
        "pp_advice":         "💡 Selling Advice",
        "pp_sell_now":       "✅ Great time to sell! Price is near peak this month.",
        "pp_sell_decent":    "📊 Decent price. Best month is",
        "pp_sell_wait":      "⏳ Consider waiting. Best price in",
        "pp_at":             "at",
        "pp_yaxis":          "Price (₹/Quintal)",
        "pp_xaxis":          "Month",
        "pp_selected_month": "Your Selected Month",

        # ── AI Chat ──────────────────────────────────────────
        "ai_title":          "🤖 AI Farm Assistant",
        "ai_subtitle":       "Ask me anything about farming, crops, diseases, or market prices!",
        "ai_quick":          "💡 Quick Questions",
        "ai_q1":             "Best crops for Black soil in Kharif season?",
        "ai_q2":             "How to treat tomato late blight?",
        "ai_q3":             "What is PM-KISAN scheme?",
        "ai_q4":             "How much water does wheat need?",
        "ai_thinking":       "Thinking...",
        "ai_placeholder":    "Ask your farming question...",
        "ai_clear":          "🗑️ Clear Chat",
        "ai_error":          "Error",
    },

    "हिंदी": {
        # ── app.py ──────────────────────────────────────────
        "subtitle":          "### आपका AI-आधारित कृषि सहायक",
        "feat_crop":         "🌱 **फसल सिफारिश**\nमिट्टी और स्थान के आधार पर फसल सुझाव पाएं",
        "feat_disease":      "🔬 **रोग पहचान**\nपत्ती की फोटो अपलोड करके रोग पहचानें",
        "feat_weather":      "🌦️ **मौसम पूर्वानुमान**\nआपके खेत का वास्तविक समय मौसम",
        "feat_ai":           "🤖 **AI कृषि सहायक**\nकृषि पर प्रशिक्षित AI से बात करें",
        "feat_price":        "📈 **मूल्य भविष्यवाणी**\nबेचने से पहले फसल का मूल्य जानें",
        "footer":            "सुविधाओं के बीच नेविगेट करने के लिए साइडबार का उपयोग करें।",

        # ── Weather ─────────────────────────────────────────
        "wt_title":          "🌦️ मौसम पूर्वानुमान",
        "wt_subtitle":       "अपने स्थान का वास्तविक समय मौसम और कृषि सलाह पाएं।",
        "wt_city":           "🏙️ शहर का नाम दर्ज करें",
        "wt_city_hint":      "जैसे: पुणे, मुंबई, नागपुर",
        "wt_btn":            "🔍 मौसम देखें",
        "wt_temp":           "🌡️ तापमान",
        "wt_feels":          "महसूस होता है",
        "wt_humidity":       "💧 आर्द्रता",
        "wt_wind":           "💨 हवा की गति",
        "wt_visibility":     "👁️ दृश्यता",
        "wt_advice":         "🌾 आज की कृषि सलाह",
        "wt_forecast":       "📅 अगले 5 घंटे का पूर्वानुमान",
        "wt_temp_short":     "तापमान",
        "wt_no_city":        "कृपया शहर का नाम दर्ज करें!",
        "wt_loading":        "मौसम डेटा प्राप्त हो रहा है...",

        # ── Crop Recommendation ──────────────────────────────
        "cr_title":          "🌱 फसल सिफारिश",
        "cr_subtitle":       "सर्वश्रेष्ठ फसल सुझाव पाने के लिए अपनी मिट्टी और स्थान की जानकारी भरें।",
        "cr_location":       "📍 स्थान और मौसम",
        "cr_district":       "जिला",
        "cr_season":         "मौसम",
        "cr_soil":           "मिट्टी का प्रकार",
        "cr_soil_params":    "🧪 मिट्टी के पैरामीटर",
        "cr_nitrogen":       "नाइट्रोजन (N)",
        "cr_phosphorus":     "फास्फोरस (P)",
        "cr_potassium":      "पोटेशियम (K)",
        "cr_ph":             "मिट्टी का pH",
        "cr_temp":           "🌡️ तापमान (°C)",
        "cr_humidity":       "💧 आर्द्रता (%)",
        "cr_rainfall":       "🌧️ वर्षा (mm)",
        "cr_btn":            "🔍 फसल सुझाएं",
        "cr_result":         "✅ अनुशंसित फसल",
        "cr_confidence":     "मॉडल सटीकता",
        "cr_about":          "के बारे में",
        "cr_water":          "💧 पानी की आवश्यकता",
        "cr_best_season":    "📅 सर्वश्रेष्ठ मौसम",
        "cr_tip":            "सुझाव",
        "cr_loading":        "आपके खेत का डेटा विश्लेषण हो रहा है...",

        # ── Disease Detection ────────────────────────────────
        "dd_title":          "🔬 फसल रोग पहचान",
        "dd_subtitle":       "AI से रोग पहचानने के लिए पत्ती की फोटो अपलोड करें।",
        "dd_upload":         "📸 पत्ती की फोटो अपलोड करें",
        "dd_uploaded":       "📷 अपलोड की गई फोटो",
        "dd_analysis":       "🧠 AI विश्लेषण",
        "dd_healthy":        "✅ पौधा स्वस्थ है!",
        "dd_diseased":       "⚠️ रोग पाया गया!",
        "dd_plant":          "🌱 पौधा",
        "dd_disease":        "🦠 रोग",
        "dd_confidence":     "📊 सटीकता",
        "dd_top3":           "📊 शीर्ष 3 अनुमान",
        "dd_treatment":      "💊 उपचार सुझाव",
        "dd_treat_err":      "🖼️ उपचार की फोटो उपलब्ध नहीं",
        "dd_shops":          "🏪 नजदीकी कृषि दुकानें",
        "dd_city":           "📍 अपना शहर/क्षेत्र लिखें",
        "dd_search":         "🔍 दुकानें खोजें",
        "dd_found":          "दुकानें मिलीं!",
        "dd_no_shops":       "कोई पंजीकृत दुकान नहीं मिली।",
        "dd_maps":           "📍 नक्शा",
        "dd_local_only":     "⚠️ रोग पहचान केवल स्थानीय रूप से उपलब्ध है।",
        "dd_run_local":      "💡 चलाएं: `streamlit run app.py`",
        "dd_google_tip":     "💡 Google Maps पर 'agro shop near me' खोजें।",
        "dd_detail":         "विवरण",
        "dd_info":           "जानकारी",

        # ── Price Prediction ─────────────────────────────────
        "pp_title":          "📈 फसल मूल्य भविष्यवाणी",
        "pp_subtitle":       "बेचने से पहले फसल का मूल्य जानें — स्मार्ट योजना बनाएं!",
        "pp_crop":           "🌾 फसल चुनें",
        "pp_season":         "📅 मौसम चुनें",
        "pp_month":          "📆 महीना",
        "pp_year":           "📅 साल",
        "pp_btn":            "🔍 मूल्य जानें",
        "pp_predicted":      "💰 अनुमानित मूल्य",
        "pp_per_quintal":    "प्रति क्विंटल",
        "pp_min":            "📉 न्यूनतम अपेक्षित",
        "pp_max":            "📈 अधिकतम अपेक्षित",
        "pp_trend":          "📊 मूल्य प्रवृत्ति — सभी 12 महीने",
        "pp_advice":         "💡 बिक्री सलाह",
        "pp_sell_now":       "✅ बेचने का सही समय! इस महीने मूल्य शिखर पर है।",
        "pp_sell_decent":    "📊 ठीक मूल्य है। सबसे अच्छा महीना है",
        "pp_sell_wait":      "⏳ प्रतीक्षा करें। सबसे अच्छा मूल्य",
        "pp_at":             "पर",
        "pp_yaxis":          "मूल्य (₹/क्विंटल)",
        "pp_xaxis":          "महीना",
        "pp_selected_month": "आपका चुना महीना",

        # ── AI Chat ──────────────────────────────────────────
        "ai_title":          "🤖 AI कृषि सहायक",
        "ai_subtitle":       "खेती, फसल, रोग या बाज़ार मूल्य के बारे में कुछ भी पूछें!",
        "ai_quick":          "💡 त्वरित प्रश्न",
        "ai_q1":             "काली मिट्टी में खरीफ के लिए सबसे अच्छी फसल?",
        "ai_q2":             "टमाटर के लेट ब्लाइट का उपचार कैसे करें?",
        "ai_q3":             "PM-KISAN योजना क्या है?",
        "ai_q4":             "गेहूं को कितना पानी चाहिए?",
        "ai_thinking":       "सोच रहा हूं...",
        "ai_placeholder":    "अपना कृषि प्रश्न पूछें...",
        "ai_clear":          "🗑️ चैट साफ करें",
        "ai_error":          "त्रुटि",
    },

    "मराठी": {
        # ── app.py ──────────────────────────────────────────
        "subtitle":          "### तुमचा AI-आधारित शेती सहाय्यक",
        "feat_crop":         "🌱 **पीक शिफारस**\nमाती आणि स्थानावर आधारित पीक सुचवणी मिळवा",
        "feat_disease":      "🔬 **रोग ओळख**\nपानाचा फोटो अपलोड करून रोग ओळखा",
        "feat_weather":      "🌦️ **हवामान अंदाज**\nतुमच्या शेतासाठी रिअल-टाइम हवामान",
        "feat_ai":           "🤖 **AI शेती सहाय्यक**\nकृषीवर प्रशिक्षित AI शी बोला",
        "feat_price":        "📈 **किंमत अंदाज**\nविकण्यापूर्वी पिकाची किंमत जाणून घ्या",
        "footer":            "वैशिष्ट्यांमध्ये नेव्हिगेट करण्यासाठी साइडबार वापरा.",

        # ── Weather ─────────────────────────────────────────
        "wt_title":          "🌦️ हवामान अंदाज",
        "wt_subtitle":       "तुमच्या स्थानाचे रिअल-टाइम हवामान आणि शेती सल्ला मिळवा.",
        "wt_city":           "🏙️ शहराचे नाव टाका",
        "wt_city_hint":      "उदा. पुणे, मुंबई, नागपूर",
        "wt_btn":            "🔍 हवामान पाहा",
        "wt_temp":           "🌡️ तापमान",
        "wt_feels":          "जाणवते",
        "wt_humidity":       "💧 आर्द्रता",
        "wt_wind":           "💨 वाऱ्याचा वेग",
        "wt_visibility":     "👁️ दृश्यमानता",
        "wt_advice":         "🌾 आजचा शेती सल्ला",
        "wt_forecast":       "📅 पुढील 5 तासांचा अंदाज",
        "wt_temp_short":     "तापमान",
        "wt_no_city":        "कृपया शहराचे नाव टाका!",
        "wt_loading":        "हवामान डेटा मिळवत आहे...",

        # ── Crop Recommendation ──────────────────────────────
        "cr_title":          "🌱 पीक शिफारस",
        "cr_subtitle":       "सर्वोत्तम पीक सुचवणीसाठी तुमची माती आणि स्थानाची माहिती भरा.",
        "cr_location":       "📍 स्थान आणि हंगाम",
        "cr_district":       "जिल्हा",
        "cr_season":         "हंगाम",
        "cr_soil":           "मातीचा प्रकार",
        "cr_soil_params":    "🧪 मातीचे मापदंड",
        "cr_nitrogen":       "नायट्रोजन (N)",
        "cr_phosphorus":     "फॉस्फरस (P)",
        "cr_potassium":      "पोटॅशियम (K)",
        "cr_ph":             "मातीचा pH",
        "cr_temp":           "🌡️ तापमान (°C)",
        "cr_humidity":       "💧 आर्द्रता (%)",
        "cr_rainfall":       "🌧️ पाऊस (mm)",
        "cr_btn":            "🔍 पीक सुचवा",
        "cr_result":         "✅ शिफारस केलेले पीक",
        "cr_confidence":     "मॉडेल अचूकता",
        "cr_about":          "बद्दल",
        "cr_water":          "💧 पाण्याची गरज",
        "cr_best_season":    "📅 सर्वोत्तम हंगाम",
        "cr_tip":            "सूचना",
        "cr_loading":        "तुमच्या शेताचा डेटा विश्लेषण होत आहे...",

        # ── Disease Detection ────────────────────────────────
        "dd_title":          "🔬 पीक रोग ओळख",
        "dd_subtitle":       "AI द्वारे रोग ओळखण्यासाठी पानाचा फोटो अपलोड करा.",
        "dd_upload":         "📸 पानाचा फोटो अपलोड करा",
        "dd_uploaded":       "📷 अपलोड केलेला फोटो",
        "dd_analysis":       "🧠 AI विश्लेषण",
        "dd_healthy":        "✅ झाड निरोगी आहे!",
        "dd_diseased":       "⚠️ रोग आढळला!",
        "dd_plant":          "🌱 झाड",
        "dd_disease":        "🦠 रोग",
        "dd_confidence":     "📊 अचूकता",
        "dd_top3":           "📊 शीर्ष 3 अंदाज",
        "dd_treatment":      "💊 उपचार सूचना",
        "dd_treat_err":      "🖼️ उपचाराचा फोटो उपलब्ध नाही",
        "dd_shops":          "🏪 जवळच्या कृषी दुकाने",
        "dd_city":           "📍 तुमचे शहर/परिसर लिहा",
        "dd_search":         "🔍 दुकाने शोधा",
        "dd_found":          "दुकाने सापडली!",
        "dd_no_shops":       "कोणतेही नोंदणीकृत दुकान सापडले नाही.",
        "dd_maps":           "📍 नकाशा",
        "dd_local_only":     "⚠️ रोग ओळख फक्त स्थानिक पातळीवर उपलब्ध आहे.",
        "dd_run_local":      "💡 चालवा: `streamlit run app.py`",
        "dd_google_tip":     "💡 Google Maps वर 'agro shop near me' शोधा.",
        "dd_detail":         "तपशील",
        "dd_info":           "माहिती",

        # ── Price Prediction ─────────────────────────────────
        "pp_title":          "📈 पीक किंमत अंदाज",
        "pp_subtitle":       "विकण्यापूर्वी पिकाची किंमत जाणून घ्या — स्मार्ट नियोजन करा!",
        "pp_crop":           "🌾 पीक निवडा",
        "pp_season":         "📅 हंगाम निवडा",
        "pp_month":          "📆 महिना",
        "pp_year":           "📅 वर्ष",
        "pp_btn":            "🔍 किंमत जाणून घ्या",
        "pp_predicted":      "💰 अंदाजित किंमत",
        "pp_per_quintal":    "प्रति क्विंटल",
        "pp_min":            "📉 किमान अपेक्षित",
        "pp_max":            "📈 कमाल अपेक्षित",
        "pp_trend":          "📊 किंमत कल — सर्व 12 महिने",
        "pp_advice":         "💡 विक्री सल्ला",
        "pp_sell_now":       "✅ विकण्याची योग्य वेळ! या महिन्यात किंमत शिखरावर आहे.",
        "pp_sell_decent":    "📊 ठीक किंमत आहे. सर्वोत्तम महिना आहे",
        "pp_sell_wait":      "⏳ थांबण्याचा विचार करा. सर्वोत्तम किंमत",
        "pp_at":             "ला",
        "pp_yaxis":          "किंमत (₹/क्विंटल)",
        "pp_xaxis":          "महिना",
        "pp_selected_month": "तुमचा निवडलेला महिना",

        # ── AI Chat ──────────────────────────────────────────
        "ai_title":          "🤖 AI शेती सहाय्यक",
        "ai_subtitle":       "शेती, पीक, रोग किंवा बाजार किंमतीबद्दल काहीही विचारा!",
        "ai_quick":          "💡 त्वरित प्रश्न",
        "ai_q1":             "काळ्या मातीत खरीप हंगामासाठी सर्वोत्तम पीक?",
        "ai_q2":             "टोमॅटोच्या उशीरा झाडीवर उपचार कसे करावे?",
        "ai_q3":             "PM-KISAN योजना काय आहे?",
        "ai_q4":             "गव्हाला किती पाणी लागते?",
        "ai_thinking":       "विचार करत आहे...",
        "ai_placeholder":    "तुमचा शेती प्रश्न विचारा...",
        "ai_clear":          "🗑️ चॅट साफ करा",
        "ai_error":          "त्रुटी",
    },
}

LANG_KEY_MAP = {"English": "en", "हिंदी": "hi", "मराठी": "mr"}

def render_language_sidebar():
    if "language" not in st.session_state:
        st.session_state.language = "English"

    with st.sidebar:
        st.markdown("### 🌐 Language / भाषा / भाषा")
        selected = st.selectbox(
            "lang_select",
            options=["English", "हिंदी", "मराठी"],
            index=["English", "हिंदी", "मराठी"].index(st.session_state.language),
            label_visibility="collapsed",
            key="lang_selector"
        )
        st.session_state.language = selected
        st.markdown("---")

    T        = TRANSLATIONS[st.session_state.language]
    lang_key = LANG_KEY_MAP[st.session_state.language]
    return T, lang_key